---
name: "CodeQL"

on:
  push:
    branches: [demo, main]
    paths-ignore:
      - '**.md'  # All markdown files in the repository
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [demo, main]
    paths-ignore:
      - '**.md'
  schedule:
    # weekly run at arbitrary time
    - cron: '43 22 * * 2'

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: ['javascript']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3    

      - name: Setup Ruby
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          ruby-version: '3.1' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 0 # Increment this number if you need to re-download cached gems

      - name: Install node.js.
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Install NPM dependencies.
        run: npm install

      - name: Build with Jekyll
        # Outputs to the './_site' directory by default
        run: bundle exec jekyll build

      - name: Upload artifact
        # Automatically uploads an artifact from the './_site' directory by default
        uses: actions/upload-pages-artifact@v2
        
      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}
    

      # Autobuild attempts to build any compiled languages  (C/C++, C#, or Java)
      # If this step fails, then remove it and run the build manually. See below
      # - name: Autobuild
      # uses: github/codeql-action/autobuild@v2

      # If the Autobuild fails above, remove it and uncomment the following
      # three lines and modify them (or add more) to build your code if your
      # project uses a compiled language

      # - run: |
      #     bundle exec jekyll build          

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
